# Setup
title:        Documentações e tutoriais
tagline:      Documentações e tutoriais sobre a integração
permalink:    /:categories/:slug
baseurl:      ""
author:
  name:       
  email:      
  url:        
github:
  repo:       https://github.com/ricardobertolo/sensediateste.github.io
plugins:
  - jekyll-multiple-languages-plugin
exclude:      ["vendor", "Gemfile*", "script", "node_modules", "tmp"]
markdown:     kramdown
languages:    ["pt", "en"]
default_lang: "pt"
language_names:
  pt: Português
  en: English
